### ISSUE TITLE
Decimal are not shown

### ISSUE THREAD

**Issue by omarsawalhah** [Abanoub-Fouad/number_to_word_arabic#1]
Hi, 
Thanks for creating this package, I am wondering if it supports fractions (i.e 100.15), I tried by nothing appeared.
Thanks

**Comment by alextransportationtest** [comment]
Hi @omarsawalhah 
thanks for your support,
The package currently supports only integer numbers
Due to the difference in the classification of the decimal numbers from one usage to another

**Example**:
 10.7 minutes means 10 minutes and 42 seconds
10.7 days means 10 days and 16 hours and 48 minutes
And 10.7 pounds means 10 pounds and 70 piasters

**same number but different meaning in the 3 cases**

**Now** you can separate the number into 2 numbers and use the function twice.
**Example**:
```
Tafqeet().convert('100');
Tafqeet().convert('15');

```

**In future**, we will provide more functions like (number to time or money)

Again thanks for your support,
Have a nice day.

**Comment by Abanoub-Fouad** [comment]
Hi @omarsawalhah 
thanks for your support,
The package currently supports only integer numbers
Due to the difference in the classification of the decimal numbers from one usage to another

**Example**:
 10.7 minutes means 10 minutes and 42 seconds
10.7 days means 10 days and 16 hours and 48 minutes
And 10.7 pounds means 10 pounds and 70 piasters

**same number but different meaning in the 3 cases**

**Now** you can separate the number into 2 numbers and use the function twice.
**Example**:
```
Tafqeet().convert('100');
Tafqeet().convert('15');
```

**In future**, we will provide more functions like (number to time or money)

Again thanks for your support,
Have a nice day.
